import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;

public class Dice {
    
    private Dice() {
    }

    
    public static int[] rollDice(int numDice, int numSides) {
        Random rand = new Random();
        int[] results = new int[numDice];

        for (int i = 0; i < numDice; i++) {
            results[i] = rand.nextInt(numSides) + 1;
        }

        return results;
    }

    
    public static void writeToFile(int[] rolls) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("previousRolls.txt", true))) {
            StringBuilder sb = new StringBuilder();
            for (int roll : rolls) {
                sb.append(roll).append(" ");
            }
            sb.append("\n");
            writer.write(sb.toString());
        } catch (IOException e) {
            System.err.println("Error writing to the file.");
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        int numDice = 6;
        int numSides = 20;

        int[] rolls = rollDice(numDice, numSides);

        for (int roll : rolls) {
            System.out.print(roll + " ");
        }
        System.out.println();

        writeToFile(rolls);
    }
}
